caput BUIL-SRVY-SYSM:H0CORE-STOP 1
caput BUIL-SRVY-SYSM:H0SYSM-STOP 1
caput CTRL-SUP-SYSM:H0CORE-STOP 1
caput CTRL-SUP-SYSM:H0PLC-STOP 1
caput CTRL-SUP-SYSM:H0SYSM-STOP 1
caput UTIL-S15-SYSM:H0CORE-STOP 1
caput UTIL-S15-SYSM:H0SYSM-STOP 1
